// Generated by gencpp from file wall_following/FindWall.msg
// DO NOT EDIT!


#ifndef WALL_FOLLOWING_MESSAGE_FINDWALL_H
#define WALL_FOLLOWING_MESSAGE_FINDWALL_H

#include <ros/service_traits.h>


#include <wall_following/FindWallRequest.h>
#include <wall_following/FindWallResponse.h>


namespace wall_following
{

struct FindWall
{

typedef FindWallRequest Request;
typedef FindWallResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FindWall
} // namespace wall_following


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wall_following::FindWall > {
  static const char* value()
  {
    return "66229cd821efb4126c80f35757f3c73e";
  }

  static const char* value(const ::wall_following::FindWall&) { return value(); }
};

template<>
struct DataType< ::wall_following::FindWall > {
  static const char* value()
  {
    return "wall_following/FindWall";
  }

  static const char* value(const ::wall_following::FindWall&) { return value(); }
};


// service_traits::MD5Sum< ::wall_following::FindWallRequest> should match
// service_traits::MD5Sum< ::wall_following::FindWall >
template<>
struct MD5Sum< ::wall_following::FindWallRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wall_following::FindWall >::value();
  }
  static const char* value(const ::wall_following::FindWallRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wall_following::FindWallRequest> should match
// service_traits::DataType< ::wall_following::FindWall >
template<>
struct DataType< ::wall_following::FindWallRequest>
{
  static const char* value()
  {
    return DataType< ::wall_following::FindWall >::value();
  }
  static const char* value(const ::wall_following::FindWallRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wall_following::FindWallResponse> should match
// service_traits::MD5Sum< ::wall_following::FindWall >
template<>
struct MD5Sum< ::wall_following::FindWallResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wall_following::FindWall >::value();
  }
  static const char* value(const ::wall_following::FindWallResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wall_following::FindWallResponse> should match
// service_traits::DataType< ::wall_following::FindWall >
template<>
struct DataType< ::wall_following::FindWallResponse>
{
  static const char* value()
  {
    return DataType< ::wall_following::FindWall >::value();
  }
  static const char* value(const ::wall_following::FindWallResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WALL_FOLLOWING_MESSAGE_FINDWALL_H
